services:
  - type: web
    name: luma-scraper
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: PUPPETEER_SKIP_DOWNLOAD
        value: "true"
